print("***Student Details***")
print(input("Enter Your Name:"))
print(input("Enter Your Roll No:"))
print(input("Enter Your Age:"))
print(input("Enter Your College Name:"))
print(input("Enter Your Address:"))
print(input("Enter Your ABC ID:"))